-- Run once in the application schema after USUARIOS exists.
CREATE TABLE USUARIO_MODULOS (
    ID_USUARIO NUMBER NOT NULL,
    MODULO VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_USUARIO_MODULOS PRIMARY KEY (ID_USUARIO, MODULO),
    CONSTRAINT FK_USUARIO_MODULOS_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIOS (ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT CK_USUARIO_MODULOS_CODE CHECK (
        MODULO IN ('DISPOSITIVOS', 'REASIGNACIONES', 'TALLER', 'USUARIOS',
                   'MANTENIMIENTO', 'INVENTARIO', 'ADMIN_TOTAL')
    )
);

-- Bootstrap the existing administrator accounts as explicit superadmins once.
INSERT INTO USUARIO_MODULOS (ID_USUARIO, MODULO)
SELECT u.ID_USUARIO, 'ADMIN_TOTAL'
FROM USUARIOS u
WHERE UPPER(TRIM(u.ROL)) = 'ADMIN'
  AND NOT EXISTS (
      SELECT 1 FROM USUARIO_MODULOS p
      WHERE p.ID_USUARIO = u.ID_USUARIO AND p.MODULO = 'ADMIN_TOTAL'
  );

COMMIT;